# Generated by Django 6.0.5 on 2026-05-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('artist', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('audio_url', models.CharField(blank=True, max_length=500)),
                ('cover_image_url', models.CharField(blank=True, max_length=500)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100)),
                ('youtube_thumbnail_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
