# Generated by Django 6.0.5 on 2026-05-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_seed_seoulody_places"),
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="places.place",
            ),
        ),
    ]
